name = "3024"

[colors]
bg_global = "#090300"

bg_focused = "#090300"
bg_unfocused = "#090300"
text_focused = "#a5a2a2"
text_secondary = "#db2d20"
text_secondary_u = "#d01b13"
text_unfocused = "#807d7c"
text_highlighted = "#fded02"
text_highlighted_u = "#e8bbd0"
border_focused = "#01a0e4"
border_unfocused = "#4a4543"
progress_complete = "#01a252"
progress_incomplete = "#3a3432"

[borders]
border_display = "all"
border_type = "thick"
