name = "Dracula"

[colors]
# Dracula color scheme
bg_global = "#282a36"
bg_focused = "#44475a"
bg_unfocused = "#282a36"

text_focused = "#f8f8f2"
text_secondary = "#ff79c6"
text_secondary_u = "#bd5f92"
text_unfocused = "#6272a4"
text_highlighted = "#8be9fd"
text_highlighted_u = "#5fa8b8"

border_focused = "#50fa7b"
border_unfocused = "#44475a"

progress_complete = "#ff5555"
progress_incomplete = "#44475a"

[borders]
border_display = "all"
border_type = "thick"