name = "Monokai Classic"

[colors]
bg_global = "#272822"
bg_focused = "#3E3D32"
bg_unfocused = "#272822"

text_focused = "#F8F8F2"
text_unfocused = "#75715E"
text_secondary = "#F92672"
text_secondary_u = "#C91D5E"
text_highlighted = "#E6DB74"
text_highlighted_u = "#B8AF5C"

border_focused = "#A6E22E"
border_unfocused = "#49483E"

progress_complete = "#F92672"
progress_incomplete = "#49483E"

[borders]
border_display = "all"
border_type = "rounded"
