name = "Monokai Shusia"

[colors]
bg_global = "#1A181A"
bg_focused = "#2D2A2E"
bg_unfocused = "#211F21"

text_focused = "#E3E1E4"
text_unfocused = "#848089"
text_secondary = "#9ECD6F"
text_secondary_u = "#394634"
text_highlighted = "#F85E84"
text_highlighted_u = "#55393D"

border_focused = "#AB9DF2"
border_unfocused = "#433D51"

progress_complete = "#ff5555"
progress_incomplete = "#44475a"

[borders]
border_display = "all"
border_type = "rounded"
