name  = "Soft Light"

[colors]
bg_global = "#fafafa"
bg_focused = "#f0f0f0"
bg_unfocused = "#e8e8e8"

text_focused = "#2d2d2d"
text_secondary = "#d73a49"
text_secondary_u = "#b31d28"
text_unfocused = "#6a737d"
text_highlighted = "#005cc5"
text_highlighted_u = "#032f62"

border_focused = "#0366d6"
border_unfocused = "#d1d5da"

progress_complete = "#28a745"
progress_incomplete = "#c8c8c8"

[borders]
border_display = "all"
border_type = "rounded"
