name = "Transparent"

[colors]
# Background colors
bg_global = ""
bg_focused = ""
bg_unfocused = ""

# Text colors
text_focused = "#D2D2D2"
text_unfocused = "#646464"
text_secondary = "#FF4646"
text_secondary_u = "#B41E1E"
text_highlighted = "#DCDC64"
text_highlighted_u = "#82823C"

# Border colors
border_focused = "#82823C"
border_unfocused = "#646464"

# Progress bar colors
progress_complete = "#FF4646"
progress_incomplete = "#646464"

[borders]
# Options: all, none
border_display = "all"

# Options: plain, rounded, double, thick
border_type = "rounded"
